
development:
  adapter: postgresql
  encoding: unicode
  database: tps_development
  host: <%= ENV['POSTGRES_HOST'] || 'localhost'  %>
  pool: 5
  username: tps
  password: lol


test:
  adapter: postgresql
  encoding: unicode
  database: tps_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost'  %>
  pool: 5
  username: tps
  password: lol


