default:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DB_DATABASE"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000
